site_name: Notes
nav:
    - Index: index.md

theme: 
  name: material

extra_css:
  - theme/materialess.css

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg